# Generated by Django 2.0.3 on 2018-04-04 02:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_place_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-22.9013763, -43.1783903), srid=4326),
        ),
    ]
