# Generated by Django 2.0.3 on 2018-04-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default='Empty', max_length=255),
            preserve_default=False,
        ),
    ]
